### ISSUE TITLE
Missing librairies

### ISSUE THREAD

**Issue by jlesage** [sgerrand/alpine-pkg-java-openjfx#1]
First, great work and thanks for providing this Alpine package!

I'm not sure if you completed the implementation yet, but I saw that the released package is missing the following libraries (available once the build is done):
```
./build/sdk/rt/lib/amd64/libprism_common.so
./build/sdk/rt/lib/amd64/libjavafx_font_pango.so
./build/sdk/rt/lib/amd64/libjavafx_font_freetype.so
./build/sdk/rt/lib/amd64/libglass.so
./build/sdk/rt/lib/amd64/libjavafx_iio.so
./build/sdk/rt/lib/amd64/libjavafx_font.so
./build/sdk/rt/lib/amd64/libprism_sw.so
./build/sdk/rt/lib/amd64/libdecora_sse.so
./build/sdk/rt/lib/amd64/libprism_es2.so
```
I think the problem is that the `APKBUILD` is using the variable `_CARCH` instead of `CARCH`.

**Comment by sgerrand** [comment]
Apologies for the delayed response. Thanks for picking these issues up. Both of those are fixed now.

**Comment by sgerrand** [comment]
Specifically, the issues you raised were resolved by:
- a84d8a5e5daa24debde83256c0979ffe994ec00d: translate `$CARCH` into what Java expects; and
- e202d0914992d11e384c24e8d738f70ba31a421e: copy the compiled libraries into their expected locations.
